/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // ---- Alluvium VendorPay design system (see DESIGN.md) ----
        surface: '#f7f9ff',
        'surface-dim': '#ccdcef',
        'surface-bright': '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#edf4ff',
        'surface-container': '#e3efff',
        'surface-container-high': '#daeafd',
        'surface-container-highest': '#d4e4f7',
        'surface-variant': '#d4e4f7',
        'on-surface': '#0d1d2b',
        'on-surface-variant': '#554336',
        'inverse-surface': '#233240',
        'inverse-on-surface': '#e8f2ff',
        outline: '#887364',
        'outline-variant': '#dbc2b0',
        'surface-tint': '#904d00',
        primary: '#8c4b00',
        'on-primary': '#ffffff',
        'primary-container': '#b06000',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb77c',
        'primary-fixed': '#ffdcc2',
        'primary-fixed-dim': '#ffb77c',
        'on-primary-fixed': '#2e1500',
        'on-primary-fixed-variant': '#6d3900',
        secondary: '#006780',
        'on-secondary': '#ffffff',
        'secondary-container': '#64d7fe',
        'on-secondary-container': '#005c73',
        'secondary-fixed': '#b8eaff',
        'secondary-fixed-dim': '#61d4fb',
        'on-secondary-fixed': '#001f28',
        'on-secondary-fixed-variant': '#004d61',
        tertiary: '#116876',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#529baa',
        'on-tertiary-container': '#002f36',
        'tertiary-fixed': '#a5eefe',
        'tertiary-fixed-dim': '#8ad2e2',
        'on-tertiary-fixed': '#001f25',
        'on-tertiary-fixed-variant': '#004e5a',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f7f9ff',
        'on-background': '#0d1d2b',

        // ---- Legacy surface aliases (pre-DESIGN.md, still referenced across the app) ----
        'surface-lowest': '#ffffff',
        'surface-low': '#f2f4f6',
        'surface-high': '#e6e8ea',
        'surface-highest': '#e0e3e5',

        // ---- Brand accent aliases used throughout the existing app (Sidebar, Button, StatusChip, etc.) ----
        navy: '#0f1d29',
        emerald: '#006c49',
        'emerald-light': '#6cf8bb',
        amber: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          DEFAULT: '#d97706',
          dark: '#b45309',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'headline-xl': ['"Source Serif 4"', 'Georgia', 'serif'],
        'headline-xl-mobile': ['"Source Serif 4"', 'Georgia', 'serif'],
        'headline-lg': ['"Source Serif 4"', 'Georgia', 'serif'],
        'headline-lg-mobile': ['"Source Serif 4"', 'Georgia', 'serif'],
        'headline-md': ['"Source Serif 4"', 'Georgia', 'serif'],
        'headline-sm': ['"Source Serif 4"', 'Georgia', 'serif'],
        'body-lg': ['Montserrat', 'system-ui', 'sans-serif'],
        'body-md': ['Montserrat', 'system-ui', 'sans-serif'],
        'body-sm': ['Montserrat', 'system-ui', 'sans-serif'],
        'label-caps': ['Montserrat', 'system-ui', 'sans-serif'],
        'label-eyebrow': ['Montserrat', 'system-ui', 'sans-serif'],
        'code-rail': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'code-mono-sm': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '54px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['34px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '42px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.005em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-eyebrow': ['11px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '700' }],
        'code-rail': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-mono-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-2': '0.125rem',
        'space-4': '0.25rem',
        'space-8': '0.5rem',
        'space-12': '0.75rem',
        'space-16': '1rem',
        'space-20': '1.25rem',
        'space-24': '1.5rem',
        'space-32': '2rem',
        'space-40': '2.5rem',
        'space-48': '3rem',
        'space-64': '4rem',
        'space-80': '5rem',
        'space-96': '6rem',
        gutter: '1.5rem',
        'margin-desktop': '3rem',
        'margin-tablet': '1.5rem',
        'margin-mobile': '1rem',
      },
      maxWidth: {
        content: '1440px',
      },
      boxShadow: {
        card: '0 1px 3px 0 rgba(15, 23, 42, 0.04)',
        dropdown: '0px 10px 15px -3px rgba(15, 23, 42, 0.05)',
      },
    },
  },
  plugins: [],
};
